2023-12-13T14:29:38.892352:Annotate:TRACE:Application:process:87 Entering process
2023-12-13T14:29:38.897298:Annotate:TRACE:AutoCommand:process:37 Entering process
2023-12-13T14:29:38.897399:Annotate:TRACE:Command:initK8sClient:211 Entering initK8sClient
2023-12-13T14:29:38.999877:Annotate:TRACE:Command:initK8sClient:223 Exiting initK8sClient with true
2023-12-13T14:29:39.000021:Annotate:TRACE:Command:getLiqidLinkage:157 Entering getLiqidLinkage
2023-12-13T14:29:39.000111:K8SClient:TRACE:K8SClient:getConfigMap:330 Entering getConfigMap namespace=default name=kubint.liqid.com
2023-12-13T14:29:39.077835:K8SClient:TRACE:K8SClient:send:590 ===>GET:http://192.168.1.220:8001/api/v1/namespaces/default/configmaps/kubint.liqid.com
2023-12-13T14:29:39.126021:K8SClient:TRACE:K8SClient:send:604 <===(GET http://192.168.1.220:8001/api/v1/namespaces/default/configmaps/kubint.liqid.com) 404
2023-12-13T14:29:39.126172:K8SClient:TRACE:K8SClient:send:606 <==={"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"kubint.liqid.com\" not found","reason":"NotFound","details":{"name":"kubint.liqid.com","kind":"configmaps"},"code":404}

2023-12-13T14:29:39.126358:Annotate:TRACE:Command:getLiqidLinkage:168 Exiting getLiqidLinkage with false
2023-12-13T14:29:39.126495:Annotate:ERROR:Application:process:117 Catching com.liqid.k8s.exceptions.ConfigurationException: No linkage exists between the Kubernetes Cluster and a Liqid Cluster.
2023-12-13T14:29:39.12733:Annotate:ERROR:Application:process:117 com.liqid.k8s.annotate.AutoCommand.process(AutoCommand.java:45)
2023-12-13T14:29:39.12733:Annotate:ERROR:Application:process:117 com.liqid.k8s.annotate.Application.process(Application.java:91)
2023-12-13T14:29:39.12733:Annotate:ERROR:Application:process:117 com.liqid.k8s.annotate.Main.main(Main.java:350)
2023-12-13T14:29:39.127483:Annotate:TRACE:Application:process:148 Exiting process
